services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: backend
    volumes:
      #- type: bind
      - ./backend/src:/home/node/app/src
      - ./backend/fonts:/home/node/app/fonts
    container_name: ammonite_backend
    expose:
      - "1234"
    ports:
      - "1234:1234"
    command: bun --watch src/index.ts
