services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: backend
    volumes:
      #- type: bind
      - ./backend/src:/home/node/app/src
      - ./backend/nodemon.json:/home/node/app/nodemon.json
      - ./backend/package.json:/home/node/app/package.json
      - ./backend/fonts:/home/node/app/fonts
      - ./backend/tools:/home/node/app/tools
    container_name: ammonite_backend
    expose:
      - "1234"
    ports:
      - "1234:1234"
      - "1235:1235"
    command: npm run dev
