export const opTable = [
  {
    Mnemonic: 'ORI to CCR',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0000000000111100',
    DataSize: 'B',
    DataType: 'I',
  },
  {
    Mnemonic: 'ORI to SR',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0000000001111100',
    DataSize: 'W',
    DataType: 'I',
  },
  {
    Mnemonic: 'ORI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00000000XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'ANDI to CCR',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0000001000111100',
    DataSize: 'B',
    DataType: 'I',
  },
  {
    Mnemonic: 'ANDI to SR',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0000001001111100',
    DataSize: 'W',
    DataType: 'I',
  },
  {
    Mnemonic: 'ANDI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00000010XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'SUBI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00000100XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'ADDI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00000110XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'EORI to CCR',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0000101000111100',
    DataSize: 'B',
    DataType: 'I',
  },
  {
    Mnemonic: 'EORI to SR',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0000101001111100',
    DataSize: 'W',
    DataType: 'I',
  },
  {
    Mnemonic: 'EORI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00001010XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'CMPI',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00001100XXXXXXXX',
    DataSize: 'A',
    DataType: 'I',
  },
  {
    Mnemonic: 'BTST',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000100000XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BCHG',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000100001XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BCLR',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000100010XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BSET',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000100011XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'MOVEP',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '0000XXX1XX001XXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'BTST',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000XXX100XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BCHG',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000XXX101XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BCLR',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000XXX110XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'BSET',
    B: 'B',
    W: '',
    L: 'L',
    Pattern: '0000XXX111XXXXXX',
    DataSize: 'B',
    DataType: 'N',
  },
  {
    Mnemonic: 'MOVEA',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '00XXXXX001XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVE',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '00XXXXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVE from SR',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0100000011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVE to CCR',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0100010011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVE to SR',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0100011011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'NEGX',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '01000000XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'CLR',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '01000010XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'NEG',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '01000100XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'NOT',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '01000110XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'EXT',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '010010001X000XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'NBCD',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0100100000XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SWAP',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0100100001000XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'PEA',
    B: '',
    W: '',
    L: 'L',
    Pattern: '0100100001XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ILLEGAL',
    B: '',
    W: '',
    L: '',
    Pattern: '0100101011111100',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'TAS',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0100101011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'TST',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '01001010XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'TRAP',
    B: '',
    W: '',
    L: '',
    Pattern: '010011100100XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'LINK',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0100111001010XXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'UNLK',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001011XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVE USP',
    B: '',
    W: '',
    L: 'L',
    Pattern: '010011100110XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'RESET',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110000',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'NOP',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110001',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'STOP',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110010',
    DataSize: 'W',
    DataType: 'I',
  },
  {
    Mnemonic: 'RTE',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110011',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'RTS',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110101',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'TRAPV',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110110',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'RTR',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111001110111',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'JSR',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111010XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'JMP',
    B: '',
    W: '',
    L: '',
    Pattern: '0100111011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MOVEM',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '01001X001XXXXXXX',
    DataSize: 'W',
    DataType: 'M',
  },
  {
    Mnemonic: 'LEA',
    B: '',
    W: '',
    L: 'L',
    Pattern: '0100XXX111XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'CHK',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0100XXX110XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'DBCC',
    B: '',
    W: 'W',
    L: '',
    Pattern: '0101XXXX11001XXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'SCC',
    B: 'B',
    W: '',
    L: '',
    Pattern: '0101XXXX11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ADDQ',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '0101XXX0XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SUBQ',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '0101XXX1XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'BRA',
    B: 'B',
    W: 'W',
    L: '',
    Pattern: '01100000XXXXXXXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'BSR',
    B: 'B',
    W: 'W',
    L: '',
    Pattern: '01100001XXXXXXXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'BCC',
    B: 'B',
    W: 'W',
    L: '',
    Pattern: '0110XXXXXXXXXXXX',
    DataSize: 'W',
    DataType: 'D',
  },
  {
    Mnemonic: 'MOVEQ',
    B: '',
    W: '',
    L: 'L',
    Pattern: '0111XXX0XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'DIVU',
    B: '',
    W: 'W',
    L: '',
    Pattern: '1000XXX011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'DIVS',
    B: '',
    W: 'W',
    L: '',
    Pattern: '1000XXX111XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SBCD',
    B: 'B',
    W: '',
    L: '',
    Pattern: '1000XXX10000XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'OR',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1000XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SUBA',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '1001XXXX11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SUBX',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1001XXX1XX00XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'SUB',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1001XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'CMPA',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '1011XXXX11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'CMPM',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1011XXX1XX001XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'EOR',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1011XXX1XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'CMP',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1011XXX0XXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MULU',
    B: '',
    W: 'W',
    L: '',
    Pattern: '1100XXX011XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'MULS',
    B: '',
    W: 'W',
    L: '',
    Pattern: '1100XXX111XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ABCD',
    B: 'B',
    W: '',
    L: '',
    Pattern: '1100XXX10000XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'EXG',
    B: '',
    W: '',
    L: 'L',
    Pattern: '1100XXX1XX00XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'AND',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1100XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ADDA',
    B: '',
    W: 'W',
    L: 'L',
    Pattern: '1101XXXX11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ADDX',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1101XXX1XX00XXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ADD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1101XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ASD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110000X11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'LSD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110001X11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ROXD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110010X11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ROD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110011X11XXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ASD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110XXXXXXX00XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'LSD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110XXXXXXX01XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ROXD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110XXXXXXX10XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'ROD',
    B: 'B',
    W: 'W',
    L: 'L',
    Pattern: '1110XXXXXXX11XXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'UNIMPLEMENTED',
    B: '',
    W: '',
    L: '',
    Pattern: '1010XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'UNIMPLEMENTED',
    B: '',
    W: '',
    L: '',
    Pattern: '1111XXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
  {
    Mnemonic: 'INVALID',
    B: '',
    W: '',
    L: '',
    Pattern: 'XXXXXXXXXXXXXXXX',
    DataSize: '',
    DataType: '',
  },
];
